# device settings
[devices]
    [devices.h1]
        name = "h1"
        ip = "10.0.0.1"
        cmd = [
            "sysctl -w net.ipv4.tcp_congestion_control=reno"
        ]
    [devices.h2]
        name = "h2"
        ip = "10.0.0.2"
        cmd = [
            "./config/host_configs/h2.sh"
        ]
    [devices.h3]
        name = "h3"
        ip = "10.0.0.3"
        cmd = [
            "./config/host_configs/h3.sh"
        ]
    [devices.h4]
        name = "h4"
        ip = "10.0.0.4"
        cmd = [
            "iperf3 -s -p 7778 -1",
            "iperf3 -s -p 7779 -1",
        ]


# switch settings
[switches]
    [switches.s1]
        name = "s1"
    [switches.s2]
        name = "s2"
    [switches.s3]
        name = "s3"
    [switches.s4]
        name = "s4"


# link settings
[links]
pairs = [
    ["h1", "s1"],
    ["h2", "s2"],
    ["h3", "s3"],
    ["s1", "s4"],
    ["s2", "s4"],
    ["s3", "s4"],
    ["s4", "h4"]
]
cmd = [
    "tc qdisc replace dev s4-eth4 root handle 10: tbf rate 20mbit burst 10000 limit 30000",
    "tc qdisc replace dev s4-eth1 root handle 10: tbf rate 20mbit burst 10000 limit 30000",
    "tc qdisc replace dev s4-eth2 root handle 10: tbf rate 20mbit burst 10000 limit 30000",
    "tc qdisc replace dev s4-eth3 root handle 10: tbf rate 20mbit burst 10000 limit 30000",
    "tc qdisc add dev s4-eth4 parent 10: handle 15: pfifo limit 45",

    "tc qdisc replace dev s1-eth2 root handle 10: tbf rate 15mbit burst 7500 limit 22500",
    "tc qdisc replace dev s2-eth2 root handle 10: tbf rate 10mbit burst 5000 limit 15000",
    "tc qdisc replace dev s3-eth2 root handle 10: tbf rate 20mbit burst 10000 limit 30000",
    
    "tc qdisc replace dev s1-eth1 root handle 10: tbf rate 15mbit burst 7500 limit 22500",
    "tc qdisc replace dev s2-eth1 root handle 10: tbf rate 10mbit burst 5000 limit 15000",
    "tc qdisc replace dev s3-eth1 root handle 10: tbf rate 20mbit burst 10000 limit 30000",
    

    "tc qdisc add dev s1-eth2 parent 10: handle 20: netem loss 0.001% delay 10ms 3ms distribution normal",
    "tc qdisc add dev s2-eth2 parent 10: handle 20: netem loss 0.001% delay 10ms 3ms distribution normal",
    "tc qdisc add dev s3-eth2 parent 10: handle 20: netem loss 0.001% delay 10ms 3ms distribution normal",

    "tc qdisc add dev s1-eth1 parent 10: handle 20: netem loss 0.001% delay 10ms 3ms distribution normal",
    "tc qdisc add dev s2-eth1 parent 10: handle 20: netem loss 0.001% delay 10ms 3ms distribution normal",
    "tc qdisc add dev s3-eth1 parent 10: handle 20: netem loss 0.001% delay 10ms 3ms distribution normal"
    
]

[monitoring]
monitoring_time = 60
monitoring_interval = 0.05
host_client = "h1"
host_server = "h4"
interface = "s4-eth4"
iperf_file_name = "iperf.json"
iperf_flags = "-b 15mbit"
queue_data_file_name = "qlen.data"
plots_dir = "plots_dir_second"

